name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.10.1
      with:
        flutter-version: '3.13.4'

    - name: Flutter pub get
      run: flutter pub get
      working-directory: flutter_crud

    - name: Flutter analyze
      run: flutter analyze
      working-directory: flutter_crud

    - name: Flutter test
      run: flutter test
      working-directory: flutter_crud

    - name: Flutter build (apk)
      run: flutter build apk --debug
      working-directory: flutter_crud

    - name: Debug environment
      run: |
        uname -a
        curl https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json
